### ISSUE TITLE
Feature request: Parameter to skip user input

### ISSUE THREAD

**Issue by Irastris** [xdanieldzd/Scarlet#4]
Hello xdanieldzd, would it be possible for you to add a parameter (--quiet or -q for example), which would skip having to press any key after Scarlet has finished converting a texture?

I ask because I have a folder full of hundreds of textures that I need converted, and so far your tool has been the only one that doesn't fail on some of them 'thus far.

I'd like to write a batch script to convert every texture in the folder automatically, but the seemingly impassable "Press any key to exit." at the end of runtime ruins that because I'd have to sit there and press any key to continue 827 times (that's how many textures I have).

Thank you if you read this, and I really hope you add this option!

**Comment by xdanieldzd** [comment]
As for the parameter, that sounds like it could be a useful feature and should be rather easy to add, so I'll look into it.

That said, you can already give the converter a whole folder as an input, instead of calling it 827 times with a single file each time. You'll still have to press a key at the end, but it'll only be one press instead of 827. Of course, if this way isn't possible with your use case, I'll still look into adding a --quiet parameter.

**Comment by Irastris** [comment]
That would be just fine, actually. The thought to specify a folder as input rather than a loop for each file completely skipped my mind.

Thanks for letting me know about that!
