### ISSUE TITLE
Unsupported GXT file

### ISSUE THREAD

**Issue by trackftv** [xdanieldzd/Scarlet#7]
Trying to convert a Terraria GXT file. Doesn't seem to parse properly.

Output:

Adding file 'filename.gxt'...

Parsing files...
 File 'filename.gxt'... unsupported file.

Operation completed in 29 milliseconds.

Press any key to exit.

**Comment by xdanieldzd** [comment]
Scarlet didn't recognize the file as a GXT file, most likely because it didn't see the required magic number (well, string in this case) "GXT" at offset 0, right at the start of the file.

Are you sure the file you're trying to convert is really a GXT? If it is, could you upload it (or a handful, if there's more than one) for me to take a look at, so that I can try to add support for it?

**Comment by trackftv** [comment]
Sure.
https://drive.google.com/open?id=0B_dquQ34ZE8GYzJxczJaanczcFk
If it helps any, they were obtained using the Infernal BMS script on a vfs2 file.

**Comment by xdanieldzd** [comment]
These don't seem to be GXT files, or at least not of the GXT format that Scarlet understands (i.e. standard PS Vita ones). For comparison's sake, here's a GXT as supported by Scarlet vs one of your sample files:

![Comparison](https://user-images.githubusercontent.com/7199225/27012942-645ebe4e-4eda-11e7-906c-720ed86bb46b.png)

Not sure if I can help you here. I'm guessing that either 1) the files are compressed in some way, 2) the script you used doesn't work properly with Terraria or 3) Terraria GXTs are actually unrelated to said standard Vita format.

**Comment by trackftv** [comment]
Alright, I'll see what I can do with these then. Thanks for your ideas.
